---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-ks
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifests
  prune: true
  targetNamespace: demo2
  sourceRef:
    kind: GitRepository
    name: source-repo
